version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - blog-network

  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - blog-network
networks:
  blog-network:
