version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: sapassword
      POSTGRES_PASSWORD: sapassword
    networks:
      - blog-network

  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: sapassword
      POSTGRES_PASSWORD: sapassword
    networks:
      - blog-network
networks:
  blog-network:
